### ISSUE TITLE
Support ALB as an event source

### ISSUE THREAD

**Issue by gsingh1** [getndazn/dazn-lambda-powertools#130]
# This is a Feature Proposal

## Description

Lambda is now supported as a target for Application Load Balancers as an alternative to API Gateway.

Example event format: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#receive-event-from-load-balancer

We can parse this event in a similar way to API Gateway and extract the Correlation IDs automatically.

**Comment by loujaybee** [comment]
I'm actually using this at the moment, could take a look at implementing.

**Comment by gsingh1** [comment]
Go for it, here is a really good resource on some payload event differences between API GW and ALB, most of it is the same however.

**Comment by loujaybee** [comment]
Thanks @gsingh1 I'll give it a swing 😁

**Comment by theburningmonk** [comment]
@loujaybee hey, have you got any update on this?

**Comment by loujaybee** [comment]
Hey @theburningmonk thanks for reaching out. Not just yet, the christmas period was a bit manic for me! Hopefully I should get a chance in the next couple of weeks.
