### ISSUE TITLE
Create Hosted Documentation

### ISSUE THREAD

**Issue by loujaybee** [getndazn/dazn-lambda-powertools#132]
# This is a Feature Proposal

## Description

When I first started using Powertools I had a bit of difficulty understanding how the different bits fit together. I like the way each lerna package is documented, but found it a bit hard to navigate between them. I think what would help is to run a static site generator over the markdown, to create a real hosted site for powertools. I'm happy to take a swing at this. 

## Other Questions

One other question would be if we're happy to proceed: What domain?

**Comment by loujaybee** [comment]
CC'ing @Granze for input.

**Comment by loujaybee** [comment]
Something like a branded GitBook?

![2019-11-21 08 45 59](https://user-images.githubusercontent.com/5528307/69321657-67a9b380-0c3b-11ea-9f03-d1a2fea57e9a.gif)

**Comment by loujaybee** [comment]
Update: Currently discussing internally where it could be hosted. I'll hold off on PR'ing until then, also need to consider branding. Will update when I know more.

**Comment by Granze** [comment]
It seems that someone already registered a Gitbook account as DAZN
![image](https://i.imgur.com/z6nuxSU.png)

**Comment by loujaybee** [comment]
@Granze is there a reason you'd want to use hosted gitbook? We can self-host if needed, it's only static files, so shouldn't be too difficult.

**Comment by Granze** [comment]
No particular reason, I just think it will be easier.

**Comment by loujaybee** [comment]
This is up now at: https://getndazn.github.io/dazn-lambda-powertools/ if you wanted to take a look @Granze ... next step would be to have a nicer domain ideally... any thoughts welcome.
