### ISSUE TITLE
Add support for url option in HTTP client

### ISSUE THREAD

**Issue by rappleg** [getndazn/dazn-lambda-powertools#141]
# This is a Feature Proposal

## Description

Depending on the HTTP client API that you are migrating from there are quite a few using the `url` option instead of `uri`. This of course is a pretty trivial change when moving to the dazn client, but adding support for `url` would make switching even simpler for people moving from clients that currently use `url`. We ran into this numerous times when migrating from [request-promise-native](https://github.com/request/request-promise-native) as it's an easy thing to overlook and would be nice to support both.

**Comment by theburningmonk** [comment]
closed by #142
