### ISSUE TITLE
dynamodb support adds aws-sdk to middleware-correlation-ids

### ISSUE THREAD

**Issue by simontabor** [getndazn/dazn-lambda-powertools#149]
# This is a Bug Report

## Description

We've noticed large bundle sizes (without using tree-shaking) for Lambda functions using middleware-correlation-ids.

This has been looked into, and it caused by the aws-sdk being installed by https://github.com/getndazn/dazn-lambda-powertools/blob/master/packages/lambda-powertools-middleware-correlation-ids/event-sources/dynamodb.js

Reporting as a bug, as it's adding 45MB bundle size for code which isn't used in our project.

Potential fixes:
- Use the aws-sdk bundled with the Lambda (DDB unmarshalling shouldn't change)
- Move the DynamoDB correlation IDs support to be a separate module, somehow

**Comment by theburningmonk** [comment]
Good catch. I think defaulting to the bundled AWS-SDK is probably the best option right now, as you said, the unmarshalling logic shouldn't change even as they add support for new API operations.
