### ISSUE TITLE
Typescript typings support

### ISSUE THREAD

**Issue by lkhari** [getndazn/dazn-lambda-powertools#158]
# Typescript support
Typing can help developers know what shape their objects will be this, may be particularly useful for being aware of __context__ in the wrapped responses.

## Description

* Typescript support for the packages. 

Of course this can be done by a third party and put into the @types package, but it might be good to own the file if any future changes are made.

**Comment by rforsyth** [comment]
Are there any examples of other projects that have created definition files for @dazn/lambda-powertools-* ?

**Comment by lkhari** [comment]
There wasn't any examples from me looking around. @rforsyth but I've done a pull request to show putting types for logger. If this goes well I may start adding types for the other packages. Or at least the ones i'm constantly using
