### ISSUE TITLE
Upgrade to Middy 1.0.0

### ISSUE THREAD

**Issue by theburningmonk** [getndazn/dazn-lambda-powertools#213]
# This is a Feature Proposal

## Description

Middy has finally reached the 1.0.0 milestone a few weeks back, so we have the modular packages which would have a bit impact on code start performance.

We should update the middleware to use middy 1.x

**Comment by lkhari** [comment]
I don't mind taking this on. Is there any particular feature we plan to get out of middy 1.0.0.

Looking at https://github.com/middyjs/middy/blob/master/UPGRADE.md
It seems like we'll just be moving to @middy/core.
