### ISSUE TITLE
LogTimeout with async handler does not log event (lambda-powertools-middleware-log-timeout)

### ISSUE THREAD

**Issue by franz101** [getndazn/dazn-lambda-powertools#219]
`const processPayment = async (event, context) => {
const wait = (ms) => {
  return new Promise(resolve => setTimeout(resolve, ms));
}
wait(6000)
 return {
  statusCode: 200,
  body: JSON.stringify({ result: 'success', message: 'payment processed correctly'})
};

const handler = middy(processPayment)
  .use(logTimeout(50))
`

Log Timeout does not seem to work with an async Handler. Is that true? There is nothing showing up in the logs.

**Comment by theburningmonk** [comment]
@franz101 what's the timeout on your function?

**Comment by theburningmonk** [comment]
I noticed in your snippet there, you're missing `await` before `wait(6000)`, maybe that's why?

**Comment by theburningmonk** [comment]
Just tested on a function myself and it worked as advertised.

```
const middy = require('@middy/core')
const logTimeout = require('@dazn/lambda-powertools-middleware-log-timeout')

module.exports.hello = middy(async event => {
  const wait = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  await wait(6000)
  return {
    statusCode: 200,
    body: JSON.stringify({ 
      result: 'success', 
      message: 'payment processed correctly'
    })
  }
}).use(logTimeout(50))
```

**Comment by franz101** [comment]
Hehe that is totally correct.

By the way I forked the repo to add the desired custom logger function:
https://github.com/franz101/middy-log-lambda-timout/blob/master/index.js
