### ISSUE TITLE
Help wanted with obfuscation

### ISSUE THREAD

**Issue by chearmstrong** [getndazn/dazn-lambda-powertools#221]
I have the following `event` from Alexa:

```JSON
{
    "directive": {
        "header": {
            "namespace": "Alexa",
            "name": "ReportState",
            "interfaceVersion": "3",
            "messageId": "1bd5d003-31b9-476f-ad03-71d471922820",
            "correlationToken": "dFMb0z+PgpgdDmluhJ1LddFvSqZ/jCc8ptlAKulUj90jSqg=="
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "this-is-what-i-want-to-remove"
            },
            "endpointId": "529de10a-c222-4440-8f6b-000000000000",
            "cookie": {}
        },
        "payload": {}
    }
}
```

I want to obfuscate the `token` in `endpoint.scope.token` but it's not working with `['directive.endpoint.scope.*.token'] as the filter.

I'm using the `@dazn/lambda-powertools-pattern-obfuscate` module like:

```JavaScript
const logger = require('@dazn/lambda-powertools-logger')
const { obfuscaterPattern: wrap } = require('@dazn/lambda-powertools-pattern-obfuscate')

const OBFUSCATIONS = ['directive.endpoint.scope.*.token']

module.exports.handler = wrap(OBFUSCATIONS, async event => {
//...
logger.debug('event', event)
//...
}
```

Am I missing something?

_On a side note, the `README` [here](https://github.com/getndazn/dazn-lambda-powertools/tree/master/packages/lambda-powertools-pattern-obfuscate#api) is wrong as it exports an object, not a function. Let me know if you want a PR._

**Comment by lkhari** [comment]
I the filter should be  `['directive.endpoint.scope.token']` 
The `*` represents for items in an array.

As for you example you've post. I don't believe the data will be removed in the pattern-obfuscate library, since it only removes the data on an error by default, (there is a parameter to do obscure the data after the function runs). If you want to obscure the data before entering the function you'll need use the middleware-obfuscator, like:

```
const logger = require('@dazn/lambda-powertools-logger')
const { obfuscaterPattern: wrap } = require('@dazn/lambda-powertools-pattern-obfuscate')
const {
  obfuscaterMiddleware,
  FILTERING_MODE,
} = require('@dazn/lambda-powertools-middleware-obfuscater');

const OBFUSCATIONS = ['directive.endpoint.scope.*.token']

module.exports.handler = wrap(OBFUSCATIONS, async event => {
//...
logger.debug('event', event)
//...
}).use(
    obfuscaterMiddleware({
      obfuscationFilters: OBFUSCATIONS,
      filteringMode: FILTERING_MODE.BLACKLIST,
      filterOnBefore: true,
    })
  );
```

**Comment by chearmstrong** [comment]
OK, that makes sense - thanks for the response. I will have a look at my options.
