### ISSUE TITLE
Allow logging to be turned off via `LOG_LEVELS` environment variable

### ISSUE THREAD

**Issue by chardos** [getndazn/dazn-lambda-powertools#230]
# This is a Feature Proposal

## Description

First of all, thanks for the awesome library, am having a good time with it so far.

Currently, when running our tests, we test a lot of failure paths, and as a result a lot of errors are logged when the tests run (please see some output below). It would be nice to be able to run the tests with `LOG_LEVEL=off` or something to that effect.

![image](https://user-images.githubusercontent.com/4082442/88339077-c2704d80-cd7c-11ea-84fb-d0829c00937b.png)

**Comment by theburningmonk** [comment]
@chardos if it's just to silence the logs during the test, how about doing something like 

`console.log = jest.fn()` 

to silence everything, that is, assuming you're using jest, if not, you can use other similar libraries to monkey-patch `console.log` during tests

**Comment by chardos** [comment]
Hi @theburningmonk, thanks for the suggestion.

We currently are doing that already in a setup file, however it feels like it is a little bit magical/hidden that way. Given that the amount of logging is controlled via the `LOG_LEVEL` variable, does it make sense to also allow disabling from there?

**Comment by theburningmonk** [comment]
I'm not sure, It's not something other loggers offer, and we've followed those existing conventions. If it only impacts testing, and there's a workaround already, then I'm hesitant to make this change.
