### ISSUE TITLE
isMatch throws error in middleware-correlation-ids when requestContext is undefined

### ISSUE THREAD

**Issue by Matthew-Myers** [getndazn/dazn-lambda-powertools#232]
# Bug on isMatching function in middleware-correlation-id/event-sources

## Events that do not have the field requestContext will error

Error thrown:
```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.isMatch (/var/task/handler/webpack:/Users/matt/Development/backend/lib/middleware/node_modules/@dazn/lambda-powertools-middleware-correlation-ids/event-sources/api-gateway.js:9:1)
    at /var/task/handler/webpack:/Users/matt/Development/backend/lib/middleware/node_modules/@dazn/lambda-powertools-middleware-correlation-ids/index.js:26:1
    at Array.find (<anonymous>)
```

Event sent to middleware:
```
{
    "__context__": {},
    "body": {...}
}
```

## Fix I have running on a forked branch
change ./packages/lambda-powertools-middleware-correlation-ids/event-sources/alb.js:6 to
```
return event.hasOwnProperty('httpMethod') && event.requestContext && event.requestContext.hasOwnProperty('elb')
```

change ./packages/lambda-powertools-middleware-correlation-ids/event-sources/api-gateway.js:6 to
```
return event.hasOwnProperty('httpMethod') && event.requestContext && !event.requestContext.hasOwnProperty('elb')
```

This will prevent you from trying to read `hasOwnProperty` from potentially undefined fields

## Additional Data

* ***Which powertool package are you using?***: lambda-powertools-middleware-correlation-ids
* ***Which version are you using?***: 1.24.1
* ***Middy engine version you're using***: @middy/core 1.0.0
* ***Operating System***: this is a lambda, deploying on macOs 10.15.6 Beta

Edit: Source of the event is from a lamda invocation

**Comment by theburningmonk** [comment]
@Matthew-Myers do you mind opening a PR? that sounds like a good change to merge in

**Comment by Matthew-Myers** [comment]
I've added the PR, feel free to let me know if there's more to be done
