### ISSUE TITLE
Node 18 Support

### ISSUE THREAD

**Issue by lkhari** [getndazn/dazn-lambda-powertools#315]
# This is a Feature Proposal
Moving forward with node 18 and aws-sdk v3

## Description

It's pretty clear this repository activity has come to a stop and with node 18 being released for lambdas using aws-sdk v3, I wanted to see if anyone wants to keep this repository alive. People could be hinted to move over to [aws-lambda-powertools-typescript](https://github.com/awslabs/aws-lambda-powertools-typescript), since it's a similar library. But it's missing some useful features like correlationIds and middleware to wire that all up. 

Of course you can say aws-lambda-powertools-typescript does have the correlationId stuff as x-ray ids, but it does occur at a financial cost to use and may not be easy to switch over for people currently using this repository.

If we do release a new major version for the support of node 18 and upgrading middy 4 and aws-sdk, should we move over to typescript as well? 

It would be good to know @theburningmonk, @simontabor and @gsingh1 opinion. Since they've been pretty big contributors and I found this through them. Not even sure if the use it, but if not maybe we redirect people to use libraries they often use

If this goes nowhere I might be tempted to port the middleware layer stuff  to typescript and build it to allow swapping out the Logger users want to use. But I wanted to gather info before commiting to a project

Edit: I didn't see this but similar thing has been mentioned on aws-lambda-powertools-typescript
https://github.com/awslabs/aws-lambda-powertools-typescript/issues/129

**Comment by dreamorosi** [comment]
Hello, maintainer of [awslabs/aws-lambda-powertools-typescript](https://github.com/awslabs/aws-lambda-powertools-typescript) here 👋 

I'm interacting with this issue only because we were mentioned, and to say that our roadmap and feature set is fully driven by users demand.

If anyone is considering using the library and notices some missing features I would recommend them to open a feature request and/or RFC based on the size. We'll be open to consider these and are always open for contributions.

**Comment by ThomSMG** [comment]
Hi! We are also very interested in this upgrade.

**Comment by mk0sojo** [comment]
Would also be interested in this. At least a AWS SDK upgrade. Happy to do a PR if anyone is around to approve it.

**Comment by mclarke-togather** [comment]
Last I heard, DAZN internally is now a skeleton crew. Would be surprised if anyone left is aware this repo exists.

**Comment by mbazalik** [comment]
Have you considered official AWS package? https://github.com/aws-powertools/powertools-lambda-typescript
