### ISSUE TITLE
dazn-datadog-metrics is not public

### ISSUE THREAD

**Issue by theburningmonk** [getndazn/dazn-lambda-powertools#51]
# This is a Bug Report

## Description

* What went wrong?

The HTTP client depends on dazn-datadog-metrics which is not public. So npm install fails:

![image](https://user-images.githubusercontent.com/546969/59914513-72ed7e80-9412-11e9-9bae-ddd2653c0469.png)

## Additional Data

* ***Which powertool package are you using?***: http-client
* ***Which version are you using?***: 1.5.1
* ***Middy engine version you're using***:
* ***Operating System***: OSX
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by theburningmonk** [comment]
@simontabor I'm interested in your opinion on this. Given how long it took to open source the powertools project, and without it the HTTP module is basically not available to anyone outside DAZN, I think the best course of action is to move the datadog-metrics module into powertools.

Alternatively, we could remove the metrics tracking from the HTTP client, but that'd be a breaking change and I'd rather avoid that (otherwise we'd break people's dashboards and alerts if they depend on the metrics from the HTTP client, and I think the metrics are useful to have).

**Comment by Rule1001** [comment]
@theburningmonk I think the change has caused a possible issue effecting tools such as @perform/lambda-powertools-correlation-ids which requires dazn-datadog-metrics as a dependancy. Can you offer any guidance?

**Comment by theburningmonk** [comment]
Hi @Rule1001, that's what this issue is about, that the `dazn-datadog-metrics` is a dependency for the HTTP client but it's not yet public. So the PR #63 is intended to address this by pulling it into this repo instead, otherwise we'd have to wait for a lengthy approval process to get the other package open sourced as well.

Apologies, I never noticed this while I was at DAZN as I had access to all DAZN packages :-(

**Comment by RenatoFranze** [comment]
Hi @theburningmonk , do you have any news regardind this bug? I really want to use this package in my project, but this dependecy is keeping me away from it. 

I saw that you alredy created a pull request to fix this situation, but, meanwhile, do you have any workaround to suggest? 

Thanks!

**Comment by cirpo** [comment]
👋we can publish that package to dazn org on npmjs.com 

@gsingh1 @simontabor are taking care of it
