### ISSUE TITLE
HTTP Client does not support timeout configuration

### ISSUE THREAD

**Issue by mike-dazn** [getndazn/dazn-lambda-powertools#56]
# This is a Feature Proposal

## Description

Superagent supports configuring a per request timeout.  This allows users to be proactive in handling unreliable 3rd party endpoints.

Currently when using this HTTP library, if an endpoint does not respond, the call hangs indefinitely.

See: https://visionmedia.github.io/superagent/#timeouts

**Comment by theburningmonk** [comment]
@mike-dazn good shout! as a temporary workaround, you can use `bluebird` to put a timeout on the `Promise` itself.

**Comment by theburningmonk** [comment]
@mike-dazn I also like to incorporate [this idea](https://theburningmonk.com/2018/01/aws-lambda-use-the-invocation-context-to-better-handle-slow-http-responses/) of using the `context.getRemainingTimeInMillis` value to auto-set timeouts as well so you always have some time for recovery.
